---
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script:
  - "rake lint"
  - "rake syntax"
  - "rake spec SPEC_OPTS='--format documentation'"
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
global:
    - PUBLISHER_LOGIN=acidprime
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
notifications:
  email: false
