---
sudo: false
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script:
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.1"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 3.8.1"

global:
    - PUBLISHER_LOGIN=acidprime
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 3.2.0"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 3.4.0"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 3.5.1"
    - rvm: jruby-19mode
      env: PUPPET_VERSION="~> 3.6.0"
notifications:
  email: false
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/8936500cc6a369ff46ee' 
    on_success: change
    on_failure: always
    on_start: false
